### ISSUE TITLE
v1 - Release Plan

### ISSUE THREAD

**Issue by soygul** [nbusy/biz#1]
**todo**: Tentative Milestones up to Apr 15, 2017: Vacation plan 2 months, basic milestone goals timetable. Also cross check biz items here with the ones in /notes folder.

Client:
- [x] Google+ login on first install.
- [x] `SqlDB` implementation to store messages/contacts/etc.
- [ ] Contact management. i.e. Search and add other people or FB friends. Or verify phone number and use phone contact list.
- [ ] New chat button and functionality depending on the implementation of contact management.
- [ ] Proper GCM implementation (needs migration to new `GCMListener`).
- [ ] Integration tests using NBusy docker image and AWS Device Farm compatible framework (native preferred but Appium acceptable).
- [ ] Automate deployment to Google Play Alpha releases. [?]
- [ ] AccountManager (prefered)/Keychain/KeyStore impl for jwt token storage, though added security of these are questionable so this is more for convenience. [?]
- [ ] Replace echo bot with proper bot endpoint. [?]

NBusy:
- [x] Vendor dependencies, and dependencies of dependencies.
- [ ] Single page @nbusy.github.io pointing to Play Store and GitHub and explaining in a sentence what NBusy is. Also open-source page pointing to top level projects and main repo.
- [ ] Replace echo bot with real chat bot. [?]
- [ ] Public logs to server for easy debugging. Might not be necessary as Play store collects crash logs to a certain extend. [?]

Titan-x:
- [ ] AWS DynamoDB (should work in local Docker dev env) and/or MongoDB provider in addition to `InMemDB`.
- [ ] Google+ auth endpoint that uses `RealDB` to store new user data and issue real JWT token (but not store it).
- [ ] GCM (now Firebase) integration. Preferably use Google's own Go GCM implementation (or Firebase Go wrapper if it has streaming), if they handle draining etc. events.
- [ ] Several refactorings: configuration, middleware, go-client, _auth & _route packages, etc.
- [ ] Implement `UseTLS()`. Heroku (or AWS) does this for us so might not be an urgency.
- [x] Ready to use Docker image, Heroku file.

Neptulon:
- [ ] Client-java: Use a queue for ws.sendMessage when async=true.
- [ ] Various refactorings and task cleanup.
- [ ] go-client.
- [x] Handle JSON-RPC error type.
- [ ] Node.js server & client for comparison. [?]

Biz:
- [ ] Complete the business plan writeup.
- [ ] Start incorporating the business by the year end.
- [ ] Research government, 3rd party boosts for tech startups.
- [ ] Research small venture capital options, [accelerators](https://www.google.com/search?q=sweden+startup&cad=h#q=sweden+startup+accelerator), etc. without share option requirements.

Misc:
- [ ] Switch to full Linux (Mint >= 18.1) environment from OS X.
- [ ] Use containers both in development and production.
- [ ] Submit libs and main project to relevant newsletters and awesome lists after stable v1.0 releases.
